# Generated by Django 4.2.2 on 2023-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(height_field=60, upload_to='pics', width_field='50'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(height_field=60, upload_to='pics', width_field='50'),
        ),
    ]
